Enable support for installing on NixOS
bergercookie/syncall pull request #120
Opened 2024-06-30 18:16 UTC by kmjayadeep

# Description

Being a deterministic OS, NixOS doesn't support installing python packages through pip. In this PR I have added nix support using `flake.nix`. I had to update the poetry lock file as the build was failing.

Fyi: Syncall was added to nixos [registry](https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/by-name/sy/syncall/package.nix#L68). But it doesn't seem to work as the optional dependencies are not installed.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

I started using this in my configuration, using the forked repo:

https://github.com/kmjayadeep/nixdots/blob/ceb205858722a0c32b5f86f7c6fa10cf1530e1bf/flake.nix#L27

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been merged and published in downstream modules

2024-06-30 18:16 UTC, kmjayadeep commented on pyproject.toml
> -typing = "^3.7.4"
this is not required for new versions of python

2024-08-10 14:14 UTC, bergercookie requested changes
Thanks @kmjayadeep for the contirbution!

I don't have strong preferences for/against Nix.
I'm happy to merge this as long as we add some sort of test in CI that verifies that the Nix build doesn't fail (i.e. a new github workflow).

More generally, I'm not a Nix user and I'm concerned I won't be able to properly maintain these recipes. Is there an advantage in keeping this configuration in this repo? If not, could you instead put it in a new repo of you own, then add a link to point from syncall's  README to that repo? This way you'll be able to properly keep these files up to date.

2024-08-10 14:14 UTC, bergercookie commented on README.md
> +  It will install `syncall` with all optional dependencies.
Could you add an example for installing `syncall` only with a handful of the optional dependencies?

2024-08-10 14:14 UTC, bergercookie commented on README.md
> +- Install on NixOS using Flakes
Could you add a link to Flakes (for users that may be unfamiliar with it)

```
[Flakes](https://nixos.wiki/wiki/Flakes)
```

2024-10-05 03:36 UTC, kmjayadeep commented
I realized that it would be difficult to maintain nix support in this repo as there are not many users using it with nix. I will try to update the upstream version in nixpkgs instead.

2024-10-05 03:36 UTC, closed without merging

2024-12-16 08:59 UTC, niksingh710 commented
@kmjayadeep are you maintaining nix package for this? 
or have any flake packaging `syncall` for nix?

I tried to package syncall with all the required packages but it throws error.
```sh
 tw_gcal_sync
2024-12-16 14:29:04.097 | ERROR    | syncall.app_utils:inform_about_app_extras:242 -
You have to install the google,tw extras for tw_gcal_sync to work.
With pip, you can do it with something like: "pip3 install syncall[google,tw]"
Exiting.
```

2024-12-16 18:09 UTC, kmjayadeep commented
@niksingh710 I'm using it like this
https://github.com/kmjayadeep/nixdots/blob/ceb205858722a0c32b5f86f7c6fa10cf1530e1bf/flake.nix#L27

2025-03-22 06:22 UTC, kqvanity commented
My build is failing (for some reason typing is still being picked up)

```

home-manager --show-trace --impure switch --flake .#desktop
warning: Git tree '/home/kqvanity/home-manager' is dirty
error: builder for '/nix/store/hcsxv52qm0v8n4i0r6hbsyv30f6lak93-python3.9-typing-3.7.4.3.drv' failed with exit code 1;
       last 25 log lines:
       > Finished executing pypaInstallPhase
       > Running phase: fixupPhase
       > shrinking RPATHs of ELF executables and libraries in /nix/store/7yqlh87v10sgdz445pfwnf0dk8szi5c7-python3.9-typing-3.7.4.3
       > checking for references to /build/ in /nix/store/7yqlh87v10sgdz445pfwnf0dk8szi5c7-python3.9-typing-3.7.4.3...
       > patching script interpreter paths in /nix/store/7yqlh87v10sgdz445pfwnf0dk8szi5c7-python3.9-typing-3.7.4.3
       > stripping (with command strip and flags -S -p) in  /nix/store/7yqlh87v10sgdz445pfwnf0dk8szi5c7-python3.9-typing-3.7.4.3/lib
       > Executing pythonRemoveTestsDir
       > Finished executing pythonRemoveTestsDir
       > Running phase: pythonCatchConflictsPhase
       > Traceback (most recent call last):
       >   File "/nix/store/ssxs0kj7akqn4yjmin0y3j7gpr0kf0fk-catch_conflicts.py", line 1, in <module>
       >     from importlib.metadata import PathDistribution
       >   File "/nix/store/ypya8hnza5cmaka8b8xkj0r26jn0m8k9-python3-3.9.21/lib/python3.9/importlib/metadata.py", line 9, in <module>
       >     import zipfile
       >   File "/nix/store/ypya8hnza5cmaka8b8xkj0r26jn0m8k9-python3-3.9.21/lib/python3.9/zipfile.py", line 7, in <module>
       >     import importlib.util
       >   File "/nix/store/ypya8hnza5cmaka8b8xkj0r26jn0m8k9-python3-3.9.21/lib/python3.9/importlib/util.py", line 2, in <module>
       >     from . import abc
       >   File "/nix/store/ypya8hnza5cmaka8b8xkj0r26jn0m8k9-python3-3.9.21/lib/python3.9/importlib/abc.py", line 17, in <module>
       >     from typing import Protocol, runtime_checkable
       >   File "/nix/store/7yqlh87v10sgdz445pfwnf0dk8szi5c7-python3.9-typing-3.7.4.3/lib/python3.9/site-packages/typing.py", line 1359, in <module>
       >     class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
       >   File "/nix/store/7yqlh87v10sgdz445pfwnf0dk8szi5c7-python3.9-typing-3.7.4.3/lib/python3.9/site-packages/typing.py", line 1007, in __new__
       >     self._abc_registry = extra._abc_registry
       > AttributeError: type object 'Callable' has no attribute '_abc_registry'
       For full logs, run 'nix log /nix/store/hcsxv52qm0v8n4i0r6hbsyv30f6lak93-python3.9-typing-3.7.4.3.drv'.
error: 1 dependencies of derivation '/nix/store/cws95vlag8q2zvnx14issjsj2779j9hx-python3.9-syncall-0.0.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ha2rrcidrmn8nr1h8qwayrr16walvhzn-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/7ciirfns6243pyh86d6s1c88r628aln4-home-manager-generation.drv' failed to build
make: *** [Makefile:3: desktop] Error 1

```

default.nix
```nix
{ poetry2nix, lib, python39, pkgs, fetchFromGitHub, ... }:
let
  p2n = poetry2nix.lib.mkPoetry2Nix { inherit pkgs; };
in
p2n.mkPoetryApplication {
  # projectDir = syncall.outPath;
  # pyproject = false;
  projectDir = fetchFromGitHub {
    owner = "bergercookie";
    repo = "syncall";
    rev = "v1.8.0";
    hash = "sha256-Uo3nwkaA0aa4pLuUowjeOeA/N1R7lWQaKHF6PlcZy2w=";
    fetchSubmodules = true;
  };
  doCheck = false;
  groups = [ "main" ];
  checkGroups = [ ];
  preferWheels = true;
  extras = [ ];
  python = python39;
  postPatch = ''
      # substituteInPlace pyproject.toml \
      # --replace 'ruff = "^0.1.14"' \
      substituteInPlace pyproject.toml \
        # --replace-fail 'typing = "^3.7.4"' "" \
        # # --replace "poetry>=0.12" poetry-core \
        # # --replace poetry.masonry.api poetry.core.masonry.api
        # --replace-fail 'PyYAML = "~5.3.1"' 'PyYAML = "^6.0"' \
        # --replace-fail 'bidict = "^0.21.4"' 'bidict = "^0.23"' \

      --replace "poetry>=0.12" poetry-core \
      --replace 'typing = "^3.7.4"' "" \
      --replace poetry.masonry.api poetry.core.masonry.api
  '';
}
```


Any idea?

2025-03-22 13:30 UTC, niksingh710 commented
@kqvanity try this https://github.com/niksingh710/ndots/blob/master/pkgs/syncall/default.nix as i am using this to get syncall packaged for me.